### ISSUE TITLE
Entity sensor.deye_inverter_mqtt_uptime (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'minutes' which is not a valid unit for the device class ('duration') it is using

### ISSUE THREAD

**Issue by Kolbi** [CarstenGrohmann/deye-mqtt-ha-plugin#1]
Protokolldetails (WARNUNG)
Logger: homeassistant.components.sensor
Quelle: components/sensor/__init__.py:731
Integration: Sensor ([Dokumentation](https://www.home-assistant.io/integrations/sensor), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
Erstmals aufgetreten: 10:32:26 (1 Vorkommnisse)
Zuletzt protokolliert: 10:32:26

Entity sensor.deye_inverter_mqtt_uptime (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'minutes' which is not a valid unit for the device class ('duration') it is using; expected one of ['min', 'h', 'd', 's', 'ms']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22

**Comment by CarstenGrohmann** [comment]
The uptime sensor provides values with the wrong unit. You can temporarily deactivate the sensor in `config.env`:

    DEYE_HA_PLUGIN_IGNORE_TOPIC_PATTERNS=uptime

I will provide a fix for this shortly.

BTW: I prefer polite and respectful communication. Opening a ticket with just an error message is not what I expect.

**Comment by Kolbi** [comment]
Thank you! Shouldn't be impolite or unrespectful, was just not sure what to tell more regarding this issue.

**Comment by CarstenGrohmann** [comment]
It's fixed in 8736043. Can you test the fixed plugin from this branch https://github.com/CarstenGrohmann/deye-mqtt-ha-plugin/tree/fix_wrong_unit_for_uptime_sensor, please.

I'll merge the change after your confirmation that the bug is gone.

**Comment by Kolbi** [comment]
Thank you, error seems to be gone.

**Comment by CarstenGrohmann** [comment]
Fixed in 8736043
